name: MittelRandomEvents
version: '${version}'
main: io.github.lijinhong11.mittelrandomevents.MittelRandomEvents
api-version: '26.1'
author: lijinhong11
description: Configurable and developer-friendly random events.
folia-supported: true
depend:
  - MittelLib
softdepend:
  - PlaceholderAPI
  - MiniPlaceholders
permissions:
  mittelrandomevents.about:
    default: op
  mittelrandomevents.view_events:
    default: op
  mittelrandomevents.view_lines:
    default: op
  mittelrandomevents.gui:
    default: op
  mittelrandomevents.create_events:
    default: op
  mittelrandomevents.create_lines:
    default: op
  mittelrandomevents.reload:
    default: op
